/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as SanidadRouteImport } from './routes/sanidad'
import { Route as ApiariosIndexRouteImport } from './routes/apiarios/index'
import { Route as ApiariosApiaryIdRouteImport } from './routes/apiarios/$apiaryId'
import { Route as ColoniasColonyIdRouteImport } from './routes/colonias/$colonyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const SanidadRoute = SanidadRouteImport.update({
  id: '/sanidad',
  path: '/sanidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiariosIndexRoute = ApiariosIndexRouteImport.update({
  id: '/apiarios/',
  path: '/apiarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiariosApiaryIdRoute = ApiariosApiaryIdRouteImport.update({
  id: '/apiarios/$apiaryId',
  path: '/apiarios/$apiaryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ColoniasColonyIdRoute = ColoniasColonyIdRouteImport.update({
  id: '/colonias/$colonyId',
  path: '/colonias/$colonyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/historico': typeof HistoricoRoute
  '/produccion': typeof ProduccionRoute
  '/sanidad': typeof SanidadRoute
  '/apiarios/$apiaryId': typeof ApiariosApiaryIdRoute
  '/colonias/$colonyId': typeof ColoniasColonyIdRoute
  '/apiarios/': typeof ApiariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/historico': typeof HistoricoRoute
  '/produccion': typeof ProduccionRoute
  '/sanidad': typeof SanidadRoute
  '/apiarios/$apiaryId': typeof ApiariosApiaryIdRoute
  '/colonias/$colonyId': typeof ColoniasColonyIdRoute
  '/apiarios': typeof ApiariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/historico': typeof HistoricoRoute
  '/produccion': typeof ProduccionRoute
  '/sanidad': typeof SanidadRoute
  '/apiarios/$apiaryId': typeof ApiariosApiaryIdRoute
  '/colonias/$colonyId': typeof ColoniasColonyIdRoute
  '/apiarios/': typeof ApiariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datos'
    | '/historico'
    | '/produccion'
    | '/sanidad'
    | '/apiarios/$apiaryId'
    | '/colonias/$colonyId'
    | '/apiarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datos'
    | '/historico'
    | '/produccion'
    | '/sanidad'
    | '/apiarios/$apiaryId'
    | '/colonias/$colonyId'
    | '/apiarios'
  id:
    | '__root__'
    | '/'
    | '/datos'
    | '/historico'
    | '/produccion'
    | '/sanidad'
    | '/apiarios/$apiaryId'
    | '/colonias/$colonyId'
    | '/apiarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatosRoute: typeof DatosRoute
  HistoricoRoute: typeof HistoricoRoute
  ProduccionRoute: typeof ProduccionRoute
  SanidadRoute: typeof SanidadRoute
  ApiariosApiaryIdRoute: typeof ApiariosApiaryIdRoute
  ColoniasColonyIdRoute: typeof ColoniasColonyIdRoute
  ApiariosIndexRoute: typeof ApiariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanidad': {
      id: '/sanidad'
      path: '/sanidad'
      fullPath: '/sanidad'
      preLoaderRoute: typeof SanidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiarios/': {
      id: '/apiarios/'
      path: '/apiarios'
      fullPath: '/apiarios/'
      preLoaderRoute: typeof ApiariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiarios/$apiaryId': {
      id: '/apiarios/$apiaryId'
      path: '/apiarios/$apiaryId'
      fullPath: '/apiarios/$apiaryId'
      preLoaderRoute: typeof ApiariosApiaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colonias/$colonyId': {
      id: '/colonias/$colonyId'
      path: '/colonias/$colonyId'
      fullPath: '/colonias/$colonyId'
      preLoaderRoute: typeof ColoniasColonyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatosRoute: DatosRoute,
  HistoricoRoute: HistoricoRoute,
  ProduccionRoute: ProduccionRoute,
  SanidadRoute: SanidadRoute,
  ApiariosApiaryIdRoute: ApiariosApiaryIdRoute,
  ColoniasColonyIdRoute: ColoniasColonyIdRoute,
  ApiariosIndexRoute: ApiariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
